### ISSUE TITLE
Add Link to the built Docs to the Readme

### ISSUE THREAD

**Issue by frastlin** [luciasoftware/lucia#21]
Hello,
When I visit the [Github readme page](https://github.com/luciasoftware/lucia) there is no link to a gh-pages build of the documentation.
I would like to see both the api and getting started docs hosted on gh-pages and linked to by the readme.

**Comment by NicklasMCHD** [comment]
Hi.

We are aware that no link have been provided on the readme for any kind of documentation. As you can see in #8 we have been trying to get lucia's documentation on readthedocs, go follow there for updates. I'm closing this issue as a duplicate, but due note, that a link to the documentation will be provided on the readme, when we get #8 resolved.
