### ISSUE TITLE
Failed pip setup

### ISSUE THREAD

**Issue by SeanTolstoyevski** [luciasoftware/lucia#36]
**Describe the bug**
Cannot find pyal in PyPI setup.

```
(venv) D:\d\github\dark_world>pip install lucia
Collecting lucia
  Using cached https://files.pythonhosted.org/packages/b4/74/d5a1ba8f21ae63fa9839b5426ee1b34bc27a667d913b707e2454c09db364/lucia-1.1.0.tar.gz
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/80/2c/3a52e7e9c097229b026b4efbe6711c600f3a84ffdc5f11fd9e7f8932368e/pygame-1.9.6-cp37-cp37m-win32.whl (4.0MB)
     |████████████████████████████████| 4.0MB 819kB/s
Collecting pycryptodomex
  Downloading https://files.pythonhosted.org/packages/98/45/66e7fbc1306eaf51421a913e2e21743ab50aee2567350626810724fe7b91/pycryptodomex-3.9.4-cp37-cp37m-win32.whl (10.1MB)
     |████████████████████████████████| 10.1MB 939kB/s
Collecting pysoundfile
  Using cached https://files.pythonhosted.org/packages/b8/d4/4c02ba1cee60e5c5c546de4761bcb7e42cba577216561067ffe40cf8fb0a/PySoundFile-0.9.0.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win32.whl
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/ce/ad/2e88f36b56f64f70c081b32fa5512dacedf12005ccb0c2d300d44dcc1215/numpy-1.17.4-cp37-cp37m-win32.whl (10.7MB)
     |████████████████████████████████| 10.7MB 1.3MB/s
Collecting sound_lib
  Using cached https://files.pythonhosted.org/packages/ee/9c/c29358c34003f8689cda6824f235519c82d88692e50d028886dd3bdfaea7/sound_lib-0.82-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pyal (from lucia) (from versions: none)
ERROR: No matching distribution found for pyal (from lucia)

````

## information:
```
windows 10, 1903 64bit
python 3.7.3-32bit (virtualenv)
"""

**Comment by NicklasMCHD** [comment]
Hi.
Just wanted to add a quick note.
I've the error with pyal and uploaded a new version to pypi.
To get the new version do:

* pip install -U lucia

Now there shouldn't be any more problems.

**Comment by SeanTolstoyevski** [comment]
Hey @NicklasMCHD,

Why are you closing the issues before you talk about the issues?
I'il test it.

But I think what you did was wrong.

**Comment by SeanTolstoyevski** [comment]
No, the problem with the pyal continues.

after git fetch.

**Comment by NicklasMCHD** [comment]
Hi.

It automatically closes the issue when I merge a pull request with a commit that states that the issue has been fixed. It is not something I do manually.
When I commit something, I have already tested it locally and when the pr are submitted (before merging) the automatic test are executed.
Hope that answers your question @SeanTolstoyevski and thanks for your issue.
edit:
If you are doing git fetch, you need to also do git pull to, so it would look something like the following.

* git fetch
* git pull

**Comment by SeanTolstoyevski** [comment]
Everything's okay,

achievements.

**Comment by NicklasMCHD** [comment]
If everything is okay, I'll close this. If this specific bug comes up again please do reopen this issue.
