### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by SeanTolstoyevski** [luciasoftware/lucia#39]
There are no tutorials for Lucia in repo and github.io.

It is not possible to understand the engine in this way.

Samples are insufficient.

Is there any documentation for Lucia?

Yours.

**Comment by NicklasTegner** [comment]
Hi.
There's documentation available at https://LuciaSoftware.github.io/lucia is it that documentation that's insufficient?
In that case, what do you suggest. A tutorial guide, or another form of documentation?

**Comment by SeanTolstoyevski** [comment]
Hi Nick,

In readme in repo, this link gives a "404 not found" error.

That's why I didn't know about this document.

Thank you very much for the link.
