### ISSUE TITLE
providing a simple way of recording audio

### ISSUE THREAD

**Issue by brightening-eyes** [luciasoftware/lucia#5]
as Both OpenAL and bass have a way of recording audio, we can implement a way to record audio through a simple interface (like the sound object).

**Comment by NicklasMCHD** [comment]
So something like the following

``
class Recorder:
    def start(self):
        pass
    def pause(self):
        pass
    def stop(self):
        pass
    def resume(self):
        pass
``

Or did you have something else in mind.

**Comment by brightening-eyes** [comment]
we can have a different class for it which returns the recorded data, or we can directly record into the sound object.

**Comment by NicklasMCHD** [comment]
We are probably going to look at this alongside #6 after we have resolved #4
