### ISSUE TITLE
Use PBR for installation

### ISSUE THREAD

**Issue by chrisnorman7** [luciasoftware/lucia#59]
IMHO, setup.py files are ugly. Would there be interest in switching to PBR for installation? I'm more than happy to try and make it work myself, then submit a PR. ATM, it doesn't even seem possible to install the code from the next branch, and there's no requirements file or anything, so even for testing (especially for new developers), I reckon it would help.

**Comment by NicklasTegner** [comment]
hi.
Before doing that, please check this: https://python-poetry.org/docs/pyproject/
And this: https://www.python.org/dev/peps/pep-0517/

Essentially, you can just do

> pip install .

or

> pip install path/to/lucia

and that is it.

**Comment by chrisnorman7** [comment]
Ah, OK, didn't even realise those existed. I just saw the setup.py file and
assumed from there.

So why do you still have all that mess in setup.py? Obviously my PR is no
longer applicable. Sorry, should have looked more into the systems you were
using before diving in.

Take care,

Chris Norman

**Comment by NicklasTegner** [comment]
If you clone the repository based on the next branch (wihtout first cloning the master), the only relating file in there is pyproject.toml and poetry.lock

If you still see a setup.py, that would be because you are either on the master branch, or have a branch based on the master branch

**Comment by chrisnorman7** [comment]
Nope, I didn't see a setup.py file. I've never heard of this new-fangled
system, so I just assumed you hadn't made a setup.py file because it wasn't
ready for production.

Thanks for the knowledge though, that's really helpful.

Take care,

Chris Norman

**Comment by NicklasTegner** [comment]
Fair enough.
I myself use poetry in all my python projects, and urge everyone else to do the same.

I'm going to close this issue, if something else comes up relating to this, feel free to reopen :)
Thanks for your contribution!

**Comment by chrisnorman7** [comment]
Shall do. Thanks again.

Take care,

Chris Norman
