### ISSUE TITLE
Add support for eax reverb to the openAl audio backend

### ISSUE THREAD

**Issue by TheGreatAthlon** [luciasoftware/lucia#6]

**Comment by brightening-eyes** [comment]
for adding different effects including reverb etc, for OpenAL we can use alEfx (though I'm not sure how much it is compatible with different sound cards), and for bass, it has support for it, though I didn't try that.

**Comment by TheGreatAthlon** [comment]
You can probably use Maggharp's OpenAL Py Lite to do it (https://bitbucket.org/magurp244/audio-code/downloads/OpenAL_Py_Lite_v1.1.zip)

**Comment by cartertemm** [comment]
I'm not as familiar with how OpenAL works, but with bass, eax reverb prematurely cuts off at the end of a file. Makes sense, but still annoying. You may have to use a mixer channel. Just something to keep in mind for anyone wanting to take this on.
